apiVersion: v2
name: maintenance-page-chart
description: Helm chart for displaying a maintence page
type: application
version: 0.1.1
appVersion: "1.16.0"
maintainers:
- name: Tim Weinekötter
  email: tim@appswithlove.com


