apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service-clusterip
  labels:
    app: maintencance-page
spec:
  selector:
    app: maintencance-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service-nodeport
  labels:
    app: maintencance-page
spec:
  selector:
    app: maintencance-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: NodePort