apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service-clusterip
  labels:
    app: maintenance-page
spec:
  selector:
    app: maintenance-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---

{{- if .Values.enableNodePortService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service-nodeport
  labels:
    app: maintenance-page
spec:
  selector:
    app: maintenance-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: NodePort
{{- end }}
