name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Change directory to maintenance-page/
      run: cd maintenance-page/

    - name: list the directory
      run: ls

    - name: Build the Docker image
      run: docker build -t weinek/maintenance-page .
